//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HostelService.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Booking
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Booking()
        {
            this.Payment = new HashSet<Payment>();
        }
        public int Receipt_ID { get; set; }
        [Required(ErrorMessage = "Укажите дату бронирования")]
        [DataType(DataType.Date)]
        public System.DateTime Receipt_date { get; set; }
        [Required(ErrorMessage = "Укажите дату заселения")]
        [DataType(DataType.Date)]
        public System.DateTime Arrival_date { get; set; }
        [Required(ErrorMessage = "Укажите дату выселения")]
        [DataType(DataType.Date)]
        public System.DateTime Departure_date { get; set; }
        [Required(ErrorMessage = "Выберите посетителя")]
        public int Client_ID { get; set; }
        [Required(ErrorMessage = "Выберите комнату")]
        public int Room_ID { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Booking_Payment Booking_Payment { get; set; }
        public virtual Room Room { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payment> Payment { get; set; }
    }
}
