//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HostelService.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Client()
        {
            this.Booking = new HashSet<Booking>();
            this.Payment = new HashSet<Payment>();
        }
    
        public int Client_ID { get; set; }
        [Required(ErrorMessage ="Укажите фамилию!")]
        public string Surname { get; set; }
        [Required(ErrorMessage = "Укажите имя!")]

        public string FName { get; set; }
        [Required(ErrorMessage = "Укажите отчество!")]
        public string Second_name { get; set; }
        [Required(ErrorMessage = "Заполните паспортные данные!")]
        [RegularExpression(@"\(?([0-9]{4})[-. ]?([0-9]{6})", ErrorMessage = "Введены некорректные данные")]

        public string Passport { get; set; }
        [Required(ErrorMessage ="Укажите контактный номер!")]
        [RegularExpression(@"^[\+]?[(]?[0-9]{3}[)]?[-\s\.]?[0-9]{3}[-\s\.]?[0-9]{4,6}$", ErrorMessage = "Некорректный номер!")]
        public string Phone { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Booking> Booking { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payment> Payment { get; set; }
    }
}
